### PR TITLE
Override filter on logo for PI

### PR DESCRIPTION
**Pull request by Alixers505**
Remove filter shading from PI logo

Before:
Screen Shot 2020-12-29 at 11 59 21 AM

After:
Screen Shot 2020-12-29 at 11 59 13 AM

### CODE REVIEW

**Comment by Alixers505** [comment]
Accidentally deleted this. Must have been cleaning up branches on my local.

**Comment by CaitlynKnudsvig** [comment]
The drop-shadow's actually a variable, so idk if we'd rather use `$theme-site-navbar-logo-drop-shadow: "";` or keep what you pushed - thoughts?

**Comment by Alixers505** [comment]
> The drop-shadow's actually a variable, so idk if we'd rather use `$theme-site-navbar-logo-drop-shadow: "";` or keep what you pushed - thoughts?

Your suggestion would be less lines of code, so preferable. I wouldn't be able to switch over to test it for at least a couple hours though. If you have time sooner, you are welcome to push up the change.

**Comment by CaitlynKnudsvig** [comment]
Nah I'm in no rush, so take your time, no worries 😄

**Review by CaitlynKnudsvig — APPROVED** [review]

**Pull request merged**
